"""
Preprocess ECG signals for the Task 2 LLM pipeline.

This script reads the instruction JSONL files generated by
`src.task2.build_llm_dataset`, loads the corresponding `.mat` ECGs,
applies the Task 1 style preprocessing/augmentation, and writes an NPZ
cache aligned with the JSON order. The downstream LLM dataset loader can
then skip on-the-fly MATLAB decoding entirely.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Sequence

import numpy as np
import pandas as pd
import scipy.io as io
from scipy.interpolate import interp1d


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATA_ROOT = PROJECT_ROOT / "data"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Preprocess mm_instructions JSONLs into cached ECG tensors."
    )
    parser.add_argument(
        "--train-jsonl",
        type=Path,
        default=None,
        help="Path to the training instruction JSONL.",
    )
    parser.add_argument(
        "--val-jsonl",
        type=Path,
        default=None,
        help="Path to the validation instruction JSONL.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_DATA_ROOT / "preprocessed",
        help="Where to store the NPZ caches (defaults to data/preprocessed/).",
    )
    parser.add_argument(
        "--train-output",
        type=Path,
        default=None,
        help="Optional explicit NPZ path for the training split.",
    )
    parser.add_argument(
        "--val-output",
        type=Path,
        default=None,
        help="Optional explicit NPZ path for the validation split.",
    )
    parser.add_argument(
        "--mat-dir",
        type=Path,
        default=DEFAULT_DATA_ROOT / "training2017",
        help="Directory that stores the original .mat ECG files.",
    )
    parser.add_argument(
        "--cv-dir",
        type=Path,
        default=DEFAULT_DATA_ROOT / "cv",
        help="Directory with cv0.csv ... cv4.csv files for label lookup.",
    )
    parser.add_argument("--target-len", type=int, default=2400, help="ECG length after crop/pad.")
    parser.add_argument("--downsample", type=int, default=3, help="Downsample factor before normalization.")
    parser.add_argument(
        "--augment-types",
        nargs="*",
        default=[],
        choices=["noise", "scale"],
        help="Which augmentations to apply to the training split.",
    )
    parser.add_argument("--augment-prob", type=float, default=0.5, help="Probability for each augmentation op.")
    parser.add_argument("--noise-std", type=float, default=0.03, help="Std dev for Gaussian noise.")
    parser.add_argument("--scale-factor", type=float, default=0.1, help="Time-scaling factor (0.1 => 0.9~1.1).")
    parser.add_argument("--seed", type=int, default=0, help="Random seed for NumPy RNG.")

    args = parser.parse_args()
    if args.train_jsonl is None and args.val_jsonl is None:
        parser.error("At least one of --train-jsonl or --val-jsonl must be provided.")
    return args


def read_jsonl(path: Path) -> List[Dict[str, str]]:
    records: List[Dict[str, str]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if not stripped:
                continue
            records.append(json.loads(stripped))
    return records


def build_label_lookup(cv_dir: Path) -> Dict[str, str]:
    lookup: Dict[str, str] = {}
    if not cv_dir.exists():
        raise FileNotFoundError(f"CV directory not found: {cv_dir}")
    for csv_path in sorted(cv_dir.glob("cv*.csv")):
        df = pd.read_csv(csv_path)
        for _, row in df.iterrows():
            lookup[str(row["file_name"])] = str(row["label"])
    if not lookup:
        raise RuntimeError(f"No labels found under {cv_dir}")
    return lookup


def load_signal(mat_dir: Path, file_name: str) -> np.ndarray:
    mat_path = mat_dir / f"{file_name}.mat"
    if not mat_path.exists():
        raise FileNotFoundError(f"ECG mat not found: {mat_path}")
    data = io.loadmat(str(mat_path))["val"]
    return np.asarray(data).reshape(-1)


def add_noise(data: np.ndarray, noise_std: float, rng: np.random.Generator) -> np.ndarray:
    noise = rng.normal(0.0, noise_std, size=data.shape)
    return data + noise


def time_scaling(data: np.ndarray, scale_factor: float, rng: np.random.Generator) -> np.ndarray:
    n = data.shape[0]
    factor = 1.0 + rng.uniform(-scale_factor, scale_factor)
    interp_fn = interp1d(np.arange(n), data, kind="linear", fill_value="extrapolate")
    new_t = np.linspace(0, n - 1, max(int(n * factor), 1))
    return interp_fn(new_t)


def crop_or_pad(data: np.ndarray, target_len: int, rng: np.random.Generator, random_crop: bool) -> np.ndarray:
    n = data.shape[0]
    if n < target_len:
        return np.pad(data, (0, target_len - n), mode="constant")
    if n > target_len:
        if random_crop:
            start = int(rng.integers(0, n - target_len + 1))
        else:
            start = (n - target_len) // 2
        return data[start : start + target_len]
    return data


def preprocess_signal(
    signal: np.ndarray,
    target_len: int,
    downsample: int,
    random_crop: bool,
    apply_noise: bool,
    apply_scale: bool,
    noise_std: float,
    scale_factor: float,
    rng: np.random.Generator,
) -> np.ndarray:
    x = signal.astype(np.float32)
    if downsample > 1:
        x = x[::downsample]
    x -= x.mean()
    x /= (x.std() + 1e-6)
    if apply_scale:
        x = time_scaling(x, scale_factor, rng)
    if apply_noise:
        x = add_noise(x, noise_std, rng)
    x = crop_or_pad(x, target_len, rng, random_crop=random_crop)
    return x.astype(np.float32)


def determine_output_path(jsonl_path: Path, override: Path | None, output_dir: Path) -> Path:
    if override is not None:
        return override
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir / f"{jsonl_path.stem}_ecg.npz"


def process_split(
    jsonl_path: Path,
    is_train: bool,
    args: argparse.Namespace,
    label_lookup: Dict[str, str],
    rng: np.random.Generator,
) -> List[Dict[str, np.ndarray | str | int]]:
    records = read_jsonl(jsonl_path)
    seen_counts = defaultdict(int)
    processed: List[Dict[str, np.ndarray | str | int]] = []

    for idx, record in enumerate(records):
        file_name = record["file_name"]
        label = label_lookup.get(file_name)
        if label is None:
            raise KeyError(f"Label for {file_name} not found in CV directory {args.cv_dir}")

        seen_counts[file_name] += 1
        is_replica = int(seen_counts[file_name] > 1)

        raw = load_signal(args.mat_dir, file_name)

        apply_noise = False
        apply_scale = False
        if is_train and args.augment_types:
            if "noise" in args.augment_types and rng.random() < args.augment_prob:
                apply_noise = True
            if "scale" in args.augment_types and rng.random() < args.augment_prob:
                apply_scale = True

        proc = preprocess_signal(
            raw,
            target_len=args.target_len,
            downsample=args.downsample,
            random_crop=is_train,
            apply_noise=apply_noise,
            apply_scale=apply_scale,
            noise_std=args.noise_std,
            scale_factor=args.scale_factor,
            rng=rng,
        )

        processed.append(
            {
                "signal": proc,
                "file_name": file_name,
                "label": label,
                "af_label": 1 if label == "A" else 0,
                "is_replica": is_replica,
                "noise_applied": int(apply_noise),
                "scale_applied": int(apply_scale),
            }
        )

        if (idx + 1) % 500 == 0:
            print(f"[{jsonl_path.name}] processed {idx + 1}/{len(records)} samples", flush=True)

    return processed


def save_npz(records: Sequence[Dict[str, np.ndarray | str | int]], output_path: Path) -> None:
    ecg = np.stack([rec["signal"] for rec in records], axis=0)
    file_names = np.array([rec["file_name"] for rec in records], dtype=object)
    label_str = np.array([rec["label"] for rec in records], dtype=object)
    af_label = np.array([rec["af_label"] for rec in records], dtype=np.int64)
    replica_mask = np.array([rec["is_replica"] for rec in records], dtype=np.int8)
    noise_mask = np.array([rec["noise_applied"] for rec in records], dtype=np.int8)
    scale_mask = np.array([rec["scale_applied"] for rec in records], dtype=np.int8)

    np.savez_compressed(
        output_path,
        ecg=ecg,
        file_name=file_names,
        label_str=label_str,
        af_label=af_label,
        is_replica=replica_mask,
        noise_applied=noise_mask,
        scale_applied=scale_mask,
    )


def write_metadata(
    output_path: Path,
    source_jsonl: Path,
    args: argparse.Namespace,
    records: Sequence[Dict[str, np.ndarray | str | int]],
) -> None:
    positives = sum(int(rec["af_label"]) for rec in records)
    meta = {
        "npz_path": str(output_path),
        "source_jsonl": str(source_jsonl),
        "total": len(records),
        "positives": positives,
        "negatives": len(records) - positives,
        "noise_augmented": sum(int(rec["noise_applied"]) for rec in records),
        "scale_augmented": sum(int(rec["scale_applied"]) for rec in records),
        "args": {
            key: (str(val) if isinstance(val, Path) else val)
            for key, val in vars(args).items()
        },
    }
    meta_path = output_path.with_suffix(".meta.json")
    with meta_path.open("w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)


def main() -> None:
    args = parse_args()
    rng = np.random.default_rng(args.seed)
    label_lookup = build_label_lookup(args.cv_dir)

    if args.train_jsonl:
        train_records = process_split(
            args.train_jsonl,
            is_train=True,
            args=args,
            label_lookup=label_lookup,
            rng=rng,
        )
        train_out = determine_output_path(args.train_jsonl, args.train_output, args.output_dir)
        save_npz(train_records, train_out)
        write_metadata(train_out, args.train_jsonl, args, train_records)
        print(f"Saved train cache to {train_out}")

    if args.val_jsonl:
        val_records = process_split(
            args.val_jsonl,
            is_train=False,
            args=args,
            label_lookup=label_lookup,
            rng=rng,
        )
        val_out = determine_output_path(args.val_jsonl, args.val_output, args.output_dir)
        save_npz(val_records, val_out)
        write_metadata(val_out, args.val_jsonl, args, val_records)
        print(f"Saved val cache to {val_out}")


if __name__ == "__main__":
    main()
